# Generated by Django 4.2.30 on 2026-07-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('event_name', models.CharField(max_length=255)),
                ('booking_date', models.CharField(max_length=50)),
                ('number_of_tickets', models.IntegerField()),
                ('total_amount', models.FloatField()),
                ('booking_status', models.CharField(default='Confirmed', max_length=50)),
                ('seats', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('organizer_name', models.CharField(max_length=255)),
                ('event_date', models.CharField(max_length=50)),
                ('event_time', models.CharField(max_length=50)),
                ('venue', models.CharField(max_length=255)),
                ('ticket_price', models.FloatField()),
                ('available_tickets', models.IntegerField()),
                ('description', models.TextField(blank=True, default='')),
                ('image_url', models.CharField(blank=True, default='', max_length=500)),
                ('rating', models.FloatField(default=4.8)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('booking_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_status', models.CharField(default='Success', max_length=50)),
                ('transaction_id', models.CharField(max_length=100)),
                ('payment_date', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(default='user', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('venue_id', models.IntegerField(primary_key=True, serialize=False)),
                ('venue_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('contact_person', models.CharField(max_length=255)),
            ],
        ),
    ]
