# Generated by Django 4.2.30 on 2026-07-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.IntegerField(primary_key=True, serialize=False)),
                ('passenger_name', models.CharField(max_length=150)),
                ('train_name', models.CharField(max_length=150)),
                ('journey_date', models.CharField(max_length=20)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('coach_type', models.CharField(max_length=50)),
                ('seat_number', models.CharField(max_length=50)),
                ('total_fare', models.FloatField()),
                ('booking_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('passenger_id', models.IntegerField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('booking_id', models.IntegerField()),
                ('passenger_name', models.CharField(max_length=150)),
                ('amount', models.FloatField()),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_status', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(max_length=100)),
                ('payment_date', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.IntegerField(primary_key=True, serialize=False)),
                ('train_name', models.CharField(max_length=150)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('departure_date', models.CharField(max_length=20)),
                ('departure_time', models.CharField(max_length=20)),
                ('arrival_date', models.CharField(max_length=20)),
                ('arrival_time', models.CharField(max_length=20)),
                ('fare', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_id', models.IntegerField(primary_key=True, serialize=False)),
                ('train_name', models.CharField(max_length=150)),
                ('train_number', models.CharField(max_length=50, unique=True)),
                ('train_type', models.CharField(max_length=50)),
                ('total_seats', models.IntegerField()),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
            ],
        ),
    ]
